import '@styles/globals';

import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Pixelify_Sans, Rubik } from 'next/font/google';

import { cn } from '@/shared/lib/classNames/classNames';

import { Providers } from './config/providers/app-provider';

const rubik = Rubik({ subsets: ['latin'], variable: '--font-rubik' });

const pixelifySans = Pixelify_Sans({
  subsets: ['latin'],
  variable: '--font-pixelifySans'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={cn(rubik.variable, pixelifySans.variable)}>
        <Providers>{children}</Providers>

        <div id='modals'></div>

        <div id='drawer'></div>
      </body>
    </html>
  );
}
